### ISSUE TITLE
Black text of folders using caja file manager

### ISSUE THREAD

**Issue by ghost** [axxapy/Adwaita-dark-gtk2#1]
Hello:
Thanks for the theme this work perfect, but using caja file manager the original text color of folders is black, this little issue disappear when i open a new tab.

**Comment by nickurak** [comment]
Out of curiosity, could you try with my fork at https://github.com/nickurak/Adwaita-dark-gtk2 ?

**Comment by axxapy** [comment]
Due to fact that gnome introduced official dark gtk-2 theme, closing it
