### ISSUE TITLE
GNOME 3.18 needs the same method as 3.20

### ISSUE THREAD

**Issue by rrthomas** [axxapy/Adwaita-dark-gtk2#6]
I just found this theme, which is very useful (thanks!). I used it to replace an earlier Adwaita dark gtk2 theme I had, which wasn't quite working properly.

I am using GNOME 3.18 as shipped with Ubuntu 16.04 (hence it probably has a lot of users!). I found that I needed to follow the instructions for GNOME 3.20; perhaps you could update the README.md to reflect this?

**Comment by axxapy** [comment]
Yep, updated it
